### PR TITLE
fix json mapping for multiple structs

### PR DESCRIPTION
**Pull request by P4N74**

### CODE REVIEW

**Comment by radare** [comment]
Cant this be done with a Derive for Serde? Looks to me like there mist be a better way to do that

**Comment by P4N74** [comment]
Not sure. I will have to look further into this tomorrow. Though the attribute for struct fields that remains same in the json format too (e.g. name), can be removed. It might make the code somewhat better.

**Comment by chinmaydd** [comment]
If we are to change field names when converting to higher level structs giving more importance to API semantics, I think @P4N74 's approach is simpler and more easier to maintain in the long run.

**Comment by chinmaydd** [comment]
@P4N74 I have committed these changes under your authorship in the [radare2-r2pipe-api](https://github.com/radare/radare2-r2pipe-api/pull/1/commits/c71d711b062f32dafb710dfbde9d39f5d7b2d0cc) repository. I hope that's fine :) I think this PR can be closed now.

**Pull request closed without merging**
