### PR TITLE
Removes higher level API functions from r2pipe.rs

### PR DESCRIPTION
**Pull request by chinmaydd**
**This is a API breaking change.** 

Bumps r2pipe to 0.5.0.

TODO:
- [x] Add README notice
- [x] Bump version
- [x] Creation of the radare2-r2pipe-api repository
- [x] Addition of r2api.rs crate code to above
- [x] ~~Stable version of the crate on Cargo~~ (Not needed, see [here](https://github.com/rust-lang/cargo/issues/1462))
- [x] radeco-lib
- [x] rune (Updated in `rsoc` branch PR)

This functionality is to be moved to a newer repository. This is in-line with the discussion [here](https://github.com/radare/r2pipe.rs/pull/18). Multiple projects require wrappers around certain specific r2 features and pancake deemed it necessary to separate the core pipe-based logic and higher level constructs into a different project.

This PR will be updated with links to PRs to other r2-based dependent repositories.

@radare have a look. This should only be merged when all of the above projects have been stabilized to use the newer API.

### CODE REVIEW

**Comment by radare** [comment]
do you prefer radare2-r2pipe-api/rust repository or just put the stuff inside radare2-r2pipe/api/rust/…

**Comment by chinmaydd** [comment]
I think either is fine. To keep up with the convention and abstain from creating additional repositories, I think adding it as folder under the name "rust" is just fine. Although, we might need to setup the test framework accordingly for each API folder.

**Comment by radare** [comment]
the repo was created, see radare2-r2pipe-api

i think it makes sense to put it in a separate place to add proper discussion about this in there and not mess the issues with r2pipe.

**Comment by chinmaydd** [comment]
@radare, I think you can merge this PR and then have look over at [radeco-lib](https://github.com/radare/radeco-lib/pull/64) and merge that as well.

**Comment by radare** [comment]
Done!

**Pull request merged**
